export const DISPLAY = Object.freeze({
  NONE: "none",
  BLOCK: "block"
});

export const CLASS_NAME = Object.freeze({
  NIGHT_MODE: "nightMode",
  POST: "post",
  POST_ACTIVE_INDICATOR: "post__indicator--active"
});

export const STORY_SCROLL_PIXELS = 500;
export const MAXIMUM_RESULT_COUNT = 10;

export const GOOGLE_SEARCH_BASE_URL = "https://www.google.com/search?q=";

export const AUTO_COMPLETE_LOCAL_KEYWORDS = [
  "JavaScript",
  "React",
  "Vue",
  "Angular",
  "Node",
  "HTML",
  "CSS",
  "TypeScript",
  "Java",
  "Python",
  "C",
  "C++",
  "C#",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "PHP",
  "Ruby",
  "Dart",
  "Scala",
  "R",
  "SQL",
  "MySQL",
  "MongoDB",
  "PostgreSQL",
  "Oracle",
  "SQLite",
  "Redis",
  "Elasticsearch",
  "Cassandra",
  "Hadoop",
  "AWS",
  "Azure",
  "Google Cloud",
  "Docker",
  "Kubernetes",
  "Linux",
  "MacOS",
  "Windows",
  "Git",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Jira",
  "Confluence",
  "Slack",
  "Trello",
  "Notion",
  "Figma",
  "Sketch",
  "Zeplin",
  "Adobe XD",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Adobe Premiere",
  "Adobe After Effects",
  "Adobe Lightroom",
  "Adobe Audition",
  "Adobe InDesign",
  "Adobe Animate",
  "Adobe Spark",
  "Adobe Dimension",
  "Adobe Character Animator",
  "Adobe Fresco",
  "Adobe Bridge",
  "Adobe Media Encoder",
  "Adobe Prelude",
  "Adobe Rush",
  "Kakao",
  "Naver",
  "Daum",
  "Tistory",
  "Naver Blog",
  "Tistory Blog",
  "Instagram",
  "Facebook",
  "Twitter",
  "YouTube",
  "Twitch",
  "Netflix",
  "Amazon",
  "Ebay",
  "AliExpress",
  "Walmart",
  "Wish",
  "Nike",
  "Adidas",
  "Apple",
  "Samsung",
  "LG",
  "Google",
  "Gucci",
  "Louis Vuitton",
  "Chanel",
  "Prada",
  "Dior",
  "Fendi",
  "Burberry",
  "Balenciaga",
  "Hermes",
  "Yves Saint Laurent",
  "Givenchy",
  "Versace",
  "Miu Miu",
  "Bottega Veneta",
  "Valentino",
  "Saint Laurent",
  "Coach",
  "Michael Kors",
  "Marc Jacobs",
  "Dolce & Gabbana",
  "Maison Margiela",
  "Off-White",
  "Balmain",
  "Tom Ford",
];